import Head from 'next/head';

import SectionIntro from '@/components/pages/index/sectionIntro';
import SectionInfo from '@/components/pages/index/sectionInfo';
import SectionTec from '@/components/pages/index/sectionTec';
import SectionAnswers from '@/components/pages/index/sectionAnswers';
import SectionWorks from '@/components/pages/index/sectionWorks';
import SectionPrice from '@/components/pages/index/sectionPrice';

export default function Home() {
  
  return (
    <>
      <Head>
        <title>Denis Atwell</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css?family=Roboto:100,100italic,300,300italic,regular,italic,500,500italic,700,700italic,900,900italic" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,regular,500,600,700,800,900,100italic,200italic,300italic,italic,500italic,600italic,700italic,800italic,900italic" rel="stylesheet" />
      </Head>

      <SectionIntro />
      <SectionInfo />
      <SectionTec />
      <SectionAnswers />
      {/* <SectionWorks /> */}
      <SectionPrice />

    </>
  )
}